Feat panels filters panels operations
Ploomes/ts-ploomes-services pull request #10
Opened 2022-08-16 19:24 UTC by alanaMartins

2022-08-17 13:02 UTC, terentinv requested changes

2022-08-17 13:02 UTC, terentinv commented on src/services/reports/PanelsFilters/library/APIContract/types/IPanelsFiltersPatch.ts
> +	PanelId: number;
Ops

2022-08-18 13:02 UTC, eduardo-pinheiro requested changes

2022-08-18 17:21 UTC, alanaMartins commented on src/services/reports/PanelsFilters/panels-filters.service.ts
> +  }
feito

2022-08-18 17:21 UTC, alanaMartins commented on src/services/reports/PanelsFilters/library/APIContract/types/IPanelsFiltersPatch.ts
> +	PanelId: number;
ver se corrigiu!!

2022-08-18 19:57 UTC, eduardo-pinheiro approved these changes

2022-08-18 19:59 UTC, merged