Create Services:
Ploomes/ts-ploomes-services pull request #11
Opened 2022-08-16 20:12 UTC by terentinv

- Filters
- IndividualPermissions
- Tables

2022-08-17 12:47 UTC, alanaMartins commented on src/services/general/IndividualPermission/index.ts
> +}
Aqui tem que exportar os types tbm, porque está sendo usado no CRMWeb

2022-08-18 12:54 UTC, eduardo-pinheiro requested changes

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Filters/filters.service.ts
> +    return this.ploomesServer.get({ url });
colocar IFilter

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Filters/filters.service.ts
> +    return this.ploomesServer.post({ url, body });
colocar IFilter

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Filters/filters.service.ts
> +    return this.ploomesServer.patch({ url, body });
colocar IFilter

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/IndividualPermission/generic-panel-individual-permission.service.ts
> +import { PloomesServer } from "../../../library";
Mover este arquivo para o individual-permission.services

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/IndividualPermission/generic-panel-individual-permission.service.ts
> +    return this.ploomesServer.post({url: this.endPointUrl, body: formattedBody});
Colocar o tipo

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Tables/tables.service.ts
> +    body.IsDataSetSync = true
Criar uma constante que clona o body, mutar a constante clonada

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Tables/tables.service.ts
> +          mountedBody.FilterId = filter.Id as number;
Mutar a constante que foi clonada no inicio

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Tables/tables.service.ts
> +          this.ploomesServer.post<ITables>({ url: this.endPointUrl, body: mountedBody }).then(resolve).catch(reject);
enviar a constante clonada

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Tables/tables.service.ts
> +      return this.ploomesServer.post<ITables>({ url: this.endPointUrl, body });
enviar a constante clonada

2022-08-18 12:54 UTC, eduardo-pinheiro commented on src/services/general/Tables/tables.service.ts
> +    return this.ploomesServer.get({ url });
Colocar tipo

2022-08-18 20:26 UTC, eduardo-pinheiro approved these changes

2022-08-18 20:28 UTC, merged