feat ServiceChartsMetricsEntities
Ploomes/ts-ploomes-services pull request #12
Opened 2022-08-17 12:34 UTC by alanaMartins

2022-08-17 13:01 UTC, terentinv requested changes

2022-08-17 13:01 UTC, terentinv commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  get = (): Promise<Partial<IFieldsEntities & { SocketName: string }>[]> => {
Aqui não poderia ser um Type?

2022-08-17 13:34 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  get = (): Promise<Partial<IFieldsEntities & { SocketName: string }>[]> => {
feito

2022-08-17 14:22 UTC, eduardo-pinheiro requested changes

2022-08-17 14:22 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +      let permissionBooleanProp: any = { ...self };
Colocar ISelf

2022-08-17 14:22 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +      permissionPath.map((pathKey: any) => {
Ver qual que é o tipo

2022-08-17 14:22 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  }
Colocar em uma função pura

2022-08-17 16:12 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +      let permissionBooleanProp: any = { ...self };
feito

2022-08-17 16:13 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +      permissionPath.map((pathKey: any) => {
feito

2022-08-18 14:58 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  }
feito

2022-08-18 14:59 UTC, alanaMartins commented
![image](https://user-images.githubusercontent.com/88676381/185427543-1ad34679-1108-42a3-8cfd-8aabff317690.png)

2022-08-18 20:42 UTC, eduardo-pinheiro requested changes

2022-08-18 20:42 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/localMetricEntities.json
> +    "PluralUnitName": "ENTITY_CONTACT_PLURAL",
O default é NOT_IMPLEMENTED

2022-08-19 12:14 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/localMetricEntities.json
> +    "PluralUnitName": "ENTITY_CONTACT_PLURAL",
feito

2022-08-22 12:44 UTC, eduardo-pinheiro requested changes

2022-08-22 12:44 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/types/IFieldsEntitiesWithSocketName.ts
> +type IFieldsEntitiesWithSocketName = IFieldsEntities & { SocketName: string };
```
type IFieldsEntitiesWithSocketName = { SocketName: string } & Pick<IFieldsEntities,
  | "Id"
  | "Name"
  | "ApiUrl"
  | "PluralUnitName"
  | "GenderId"
>;
```

2022-08-22 12:44 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  get = (): Promise<Partial<IFieldsEntitiesWithSocketName>[]> => {
Remover Partial

2022-08-22 12:44 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetricsEntities/index.ts
> +
Exportar IFieldsEntitiesWithSocketName

2022-08-22 12:46 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/types/IFieldsEntitiesWithSocketName.ts
> +type IFieldsEntitiesWithSocketName = IFieldsEntities & { SocketName: string };
feito

2022-08-22 12:47 UTC, alanaMartins commented on src/services/reports/ChartsMetricsEntities/charts-metrics-entities.service.ts
> +  get = (): Promise<Partial<IFieldsEntitiesWithSocketName>[]> => {
feito

2022-08-22 13:01 UTC, eduardo-pinheiro approved these changes

2022-08-22 13:01 UTC, merged