Fix services path sync chart generator
Ploomes/ts-ploomes-services pull request #4
Opened 2022-08-15 18:58 UTC by alanaMartins

2022-08-17 13:52 UTC, terentinv requested changes

2022-08-17 13:52 UTC, terentinv commented on src/services/reports/ChartGenerator/chart-generator.service.ts
> +  private postEndPointUrlFunnelReports = 'PipelineReports';
Aqui pode ser só endPointUrl

2022-08-17 14:41 UTC, alanaMartins commented on src/services/reports/ChartGenerator/chart-generator.service.ts
> +  private postEndPointUrlFunnelReports = 'PipelineReports';
feito

2022-08-18 13:07 UTC, eduardo-pinheiro requested changes

2022-08-18 16:21 UTC, alanaMartins commented on src/services/reports/ChartGenerator/chart-generator.service.ts
> +    });
feito

2022-08-18 16:24 UTC, alanaMartins commented on src/services/reports/ChartGenerator/chart-generator.service.ts
> +  addBatchToQueue = (batch: Omit<IReportsChartGeneratorBatch, 'service'>) => {
feito

2022-08-18 20:05 UTC, eduardo-pinheiro approved these changes

2022-08-18 20:06 UTC, merged