Create services ChartMetrics and ChartGeneratorCache
Ploomes/ts-ploomes-services pull request #5
Opened 2022-08-15 20:44 UTC by terentinv

2022-08-17 13:06 UTC, alanaMartins approved these changes

2022-08-18 13:37 UTC, eduardo-pinheiro requested changes

2022-08-18 13:37 UTC, eduardo-pinheiro commented on src/services/reports/ChartGeneratorCache/index.ts
> +import { PloomesServer } from '../../../library';
Colocar em um arquivo ServiceChartGeneratorCache, enfim, fazer no padrão.

2022-08-18 13:37 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetrics/index.ts
> +import { IPanelsChartsMetrics } from "@ploomes/ts-ploomes-api-types";
Não pode estar dentro do index

2022-08-18 13:37 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetrics/index.ts
> +  patchOrdination = (id: number,  body: Partial<IPanelsChartsMetrics>) => {
trocar este body por ordination:number

2022-08-18 13:37 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetrics/index.ts
> +    const formattedBody: Partial<Omit<IPanelsChartsMetrics, "Values">> = new PanelChartMetric(body).createPatchOrdinationObject();
Não precisa de contract constructor

2022-08-19 14:35 UTC, eduardo-pinheiro requested changes

2022-08-19 14:35 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetrics/charts-metrics.service.ts
> +  }
A unica propriedade desse body que você usa é o body.Ordination.
Então é melhor receber um ordination: number do que um body:Partial<IPanelsChartsMetrics>

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartGeneratorCache/index.ts
> +import { PloomesServer } from '../../../library';
Done.

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartsMetrics/index.ts
> +import { IPanelsChartsMetrics } from "@ploomes/ts-ploomes-api-types";
Done.

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartsMetrics/index.ts
> +  patchOrdination = (id: number,  body: Partial<IPanelsChartsMetrics>) => {
Done

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartsMetrics/index.ts
> +    const formattedBody: Partial<Omit<IPanelsChartsMetrics, "Values">> = new PanelChartMetric(body).createPatchOrdinationObject();
Done

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartsMetrics/charts-metrics.service.ts
> +  }
Done

2022-08-19 19:51 UTC, terentinv commented on src/services/reports/ChartsMetrics/charts-metrics.service.ts
> +  }
Done

2022-08-22 12:29 UTC, eduardo-pinheiro requested changes

2022-08-22 12:29 UTC, eduardo-pinheiro commented on src/services/reports/ChartGeneratorCache/index.ts
> +
exportar tipo IChartGeneratedToCache

2022-08-22 12:29 UTC, eduardo-pinheiro commented on src/services/reports/ChartsMetrics/charts-metrics.service.ts
> +  }
Trocar body por ordination

2022-08-22 12:49 UTC, eduardo-pinheiro approved these changes

2022-08-22 12:50 UTC, merged