Fix reports panel filter types reports panels
Ploomes/ts-ploomes-services pull request #8
Opened 2022-08-16 16:51 UTC by alanaMartins

2022-08-17 13:35 UTC, terentinv approved these changes

2022-08-18 13:21 UTC, eduardo-pinheiro requested changes

2022-08-18 13:21 UTC, eduardo-pinheiro commented on src/services/reports/PanelFilterTypes/panel-filter-types.service.ts
> +    });
Colocar em uma linha

2022-08-18 13:21 UTC, eduardo-pinheiro commented on src/services/reports/Panels/panels.service.ts
> +  }
enter

2022-08-18 16:17 UTC, alanaMartins commented on src/services/reports/PanelFilterTypes/panel-filter-types.service.ts
> +    });
feito

2022-08-18 16:18 UTC, alanaMartins commented on src/services/reports/Panels/panels.service.ts
> +  }
feito

2022-08-18 20:11 UTC, eduardo-pinheiro approved these changes

2022-08-18 20:13 UTC, merged