Create new services
Ploomes/ts-ploomes-services pull request #9
Opened 2022-08-16 17:19 UTC by terentinv

2022-08-17 12:54 UTC, alanaMartins approved these changes

2022-08-17 14:33 UTC, eduardo-pinheiro requested changes

2022-08-17 14:33 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/APIContract/drilldown-api-contract.class.ts
> +class APIContractDrillDown implements IAPIContract<any,any> {
Colocar tipos

2022-08-17 14:33 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/APIContract/drilldown-api-contract.class.ts
> +class APIContractDrillDown implements IAPIContract<any,any> {
Tirar [Drilldown]

2022-08-17 14:33 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/drilldown.service.ts
> +  };
Remover esta função

2022-08-17 14:33 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/drilldown.service.ts
> +    const params = this.getParams({ Page, PageSize });
receber Page e PageSize como propriedade e montar a string da url na mão

2022-08-17 20:02 UTC, terentinv commented on src/services/reports/DrillDown/APIContract/drilldown-api-contract.class.ts
> +class APIContractDrillDown implements IAPIContract<any,any> {
Done

2022-08-17 20:04 UTC, terentinv commented on src/services/reports/DrillDown/APIContract/drilldown-api-contract.class.ts
> +class APIContractDrillDown implements IAPIContract<any,any> {
Done

2022-08-18 13:16 UTC, eduardo-pinheiro requested changes

2022-08-18 13:16 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/drilldown.service.ts
> +
Remover esta linha

2022-08-18 13:16 UTC, eduardo-pinheiro commented on src/services/reports/DrillDown/drilldown.service.ts
> +  post = (body: IDrilldownRequest) => {
get

2022-08-18 13:16 UTC, eduardo-pinheiro commented on src/services/reports/PanelFilterMetrics/panel-filter-metrics.service.ts
> +  }
?

2022-08-18 13:16 UTC, eduardo-pinheiro commented on src/services/reports/PanelFilterMetrics/panel-filter-metrics.service.ts
> +  getAllByMetricId = (metricId: number) => {
Enter

2022-08-19 13:28 UTC, terentinv commented on src/services/reports/DrillDown/drilldown.service.ts
> +
Done

2022-08-19 13:32 UTC, terentinv commented on src/services/reports/DrillDown/drilldown.service.ts
> +  post = (body: IDrilldownRequest) => {
Done

2022-08-19 13:33 UTC, terentinv commented on src/services/reports/PanelFilterMetrics/panel-filter-metrics.service.ts
> +  getAllByMetricId = (metricId: number) => {
Done

2022-08-22 12:53 UTC, eduardo-pinheiro approved these changes

2022-08-22 12:54 UTC, merged